<a href="https://colab.research.google.com/github/NeelamAkhila/1stproject/blob/main/End_to_End_E_commerce_Sales_Data_Analysis_using_Python%2C_SQL_%26_Power_BI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
from google.colab import files
uploaded=files.upload()

Saving ECOMMERS SALES.csv to ECOMMERS SALES (1).csv

In [21]:
import pandas as pd
df=pd.read_csv("ECOMMERS SALES.csv")
df.head()

,Order_ID,Order_Date,Product_Name,Category,Quantity,Unit_Price,Total_Sales,Region,Customer_Type,Payment_Method
0,1001,02-01-2025,Laptop,Electronics,1,40685,40685,Hyderabad,New,UPI
1,1002,03-01-2025,Headphones,Electronics,3,3647,10941,Bangalore,Returning,Card
2,1003,04-01-2025,Shoes,Fashion,2,2849,5698,Chennai,New,COD
3,1004,05-01-2025,Watch,Other,1,3741,3741,Mumbai,Premium,UPI
4,1005,06-01-2025,Mobile Case,Other,5,464,2320,Delhi,New,UPI

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        499 non-null    int64
 1   Order_Date      499 non-null    object
 2   Product_Name    499 non-null    object
 3   Category        499 non-null    object
 4   Quantity        499 non-null    int64
 5   Unit_Price      499 non-null    int64
 6   Total_Sales     499 non-null    int64
 7   Region          499 non-null    object
 8   Customer_Type   499 non-null    object
 9   Payment_Method  499 non-null    object
dtypes: int64(4), object(6)
memory usage: 39.1+ KB

In [23]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Product_Name      0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
Region            0
Customer_Type     0
Payment_Method    0
dtype: int64

In [24]:
df["Total_Sales"].sum()

np.int64(9459869)

In [25]:
df.groupby("Product_Name")["Total_Sales"].sum().sort_values(ascending=False)

Product_Name
Laptop          4052338
Tablet          2121830
Watch           1586564
Smartwatch       694753
Headphones       294798
Shoes            292075
Backpack         197671
Book              80947
Mobile Case       78046
Water Bottle      60847
Name: Total_Sales, dtype: int64

In [26]:
df.groupby("Region")["Total_Sales"].sum()

Region
Bangalore     492469
Chennai       986828
Delhi          78046
Hyderabad    6174168
Mumbai       1647411
Pune           80947
Name: Total_Sales, dtype: int64

In [27]:
df["Total_Sales"].mean()

np.float64(18957.653306613225)

In [28]:
df.groupby("Payment_Method")["Total_Sales"].sum()

Payment_Method
COD      433869
Card    3111381
UPI     5914619
Name: Total_Sales, dtype: int64

In [29]:
df.groupby("Product_Name")["Total_Sales"].sum().sort_values().head()

Product_Name
Water Bottle     60847
Mobile Case      78046
Book             80947
Backpack        197671
Shoes           292075
Name: Total_Sales, dtype: int64

In [30]:
df.groupby("Customer_Type")["Total_Sales"].sum()

Customer_Type
New          4564253
Premium      2281317
Returning    2614299
Name: Total_Sales, dtype: int64